import express from "express";
import { protect } from "../middleware/authMiddleware.js";
import { createPost, getPosts, getPostById, updatePost, deletePost, likePost, addComment } from "../controllers/postController.js";
const router = express.Router();
router.get("/", protect, getPosts);
router.post("/", protect, createPost);
router.get("/:id", protect, getPostById);
router.put("/:id", protect, updatePost);
router.delete("/:id", protect, deletePost);
router.post("/:id/like", protect, likePost);
router.post("/:id/comment", protect, addComment);
export default router;
